# Generated by Django 5.1.6 on 2025-06-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_publish_profile', 'Can publish profile')]},
        ),
    ]
